apiVersion: v1
kind: Pod
metadata:
  name: bim-chat-app
  labels:
    app: bim-chat-app
spec:
  containers:
  - name: app
    image: docker.io/brandon596/bim-chat
    env:
    - name: YOUTUBE_DATA_API_KEY
      value: ${YOUTUBE_DATA_API_KEY}
    - name: SECRET_KEY
      value: ${SECRET_KEY}
    - name: API_KEY
      value: ${API_KEY}
    - name: PLAYLIST_ID
      value: ${PLAYLIST_ID}
    - name: DIRECT_LINE_SECRET
      value: ${DIRECT_LINE_SECRET}
    volumeMounts:
    - name: app-data
      mountPath: /app/persistent
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m" # 0.5 CPU
      limits:
        memory: "1Gi"
        cpu: "3" # 1 CPU

  - name: cloudflare-tunnel
    image: docker.io/cloudflare/cloudflared
    args: ["tunnel", "--no-autoupdate", "--protocol", "http2", "--url", "http://localhost:8001"]
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m" # 0.25 CPU
      limits:
        memory: "512Mi"
        cpu: "500m" # 0.5 CPU

  volumes:
  - name: app-data
    emptyDir: {}